#!/bin/bash


# Setup Hostname

sudo hostnamectl set-hostname "sonar.cloudbinary.io"


# Update the hostname part of Host File

echo "`hostname -I | awk '{ print $1 }'` `hostname`" >> /etc/hosts #for set hostname perminently


# Update Ubuntu Repository

sudo apt update #apt is a package managment and its  in ubuntu


# Download, & Install Utility Softwares

sudo apt install git wget unzip curl tree -y  


# Download, Install Java 11

sudo apt install openjdk-11-jdk -y


# Backup the Environment File

sudo cp -pvr /etc/environment "/etc/environment_$(date +%F_%R)"
 #ls -lrt /etc/environment* #for back up

# Create Environment Variables

echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/" >> /etc/environment


# Compile the Configuration

source /etc/environment


# Create a Dedicated user for Sonarqube
#before creating grup user data base file if have to check avialble or  not
grep sonarh2s /etc/passwd /etc/shadow /etc/group /etc/gshadow

sudo adduser --system --no-create-home --group --disabled-login sonarh2s  #hear creating users and gurps   and creating user with this name (sonarh2s)

grep sonarh2s /etc/passwd /etc/shadow /etc/group /etc/gshadow #checking after creation
# RDBMS - Install PostgreSQL Database

wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo apt-key add -


# Add repo:

echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list  #key for perticular software


sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' #updated perticular software keys

#ls -lrt /etc/apt/sources.list   path for  sql

# Install PostgreSQL 13
#sudo apt update

sudo apt install postgresql-13


# You can check the status of its service using


sudo systemctl status postgresql
 #  grep postgres /etc/passwd /etc/shadow here cheking default passwd and grup

# Assign a Password to postgres user

passwd postgres # here it is passwd and user name


# Switch as postgres user

su - postgres

#show databases  
psql
# Check Schemas :

select schema_name from information_schema.schemata;


exit;


# Now, create a new user that will access the database for Sonarqube.

createuser sonaruser

#verify user after creation  of user greo /etc/group /etc/passwd
# Switch to the PostgreSQL shell.

psql


# To secure a newly created user, set a password for the same using the below syntax:


ALTER USER sonaruser WITH ENCRYPTED password 'Azure@123456';


Note: change the bold items with whatever you want to use.


# Create a new database on PostgreSQL by running:


CREATE DATABASE sonardb OWNER sonaruser;


# To exit from database

postgres=# \q


# OR


postgres=# exit;


# To come out from postgres user from linux server

postgres@sonar:~$ exit

logout


# Download and Setup SonarQube

wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.0.1.46107.zip


unzip sonarqube-9.0.1.46107.zip


mv sonarqube-9.0.1.46107 sonarqube


# Set user permission: We have created a dedicated user for SonarQube, hence, give the extracted permission to that user.


sudo chown -R sonarh2s:sonarh2s /opt/sonarqube
# configure database for sonar
#1 open the configuration file:
ls -lrt /opt/sonarqube/conf/sonar.properties #for varification file
cp -pvr /opt/sonarqube/conf/sonar.properties /opt/sonarqube/conf/sonar.properties_20230103
sudo vi /opt/sonarqube/conf/sonar.properties #here editing configuration path

#it isn for confiugration
sonar.jdbc.username=sonaruser
sonar.jdbc.password=Azure@123456
sonar.jdbc.url=jdbc:postgreql://localhost/sonardb
sonar.web.javadditionalopts=-server
#create a sonarqube systemd srvice file
#by defaullt there will be no service file for sonarqube to start it in the background and with system boot
# hence we to create one manually.here it
sudo vi /etc/systemd/system/sonar.service

#in vi editor we should upload
[unit]
Description=sonarQube service
After=syslog.target network.target
  
[service]

type=forking
ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
execstop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
limitNOFILE=65536
limitNPROC=4096
User=sonarh2s
Group=sonarh2s
Restart=on-failure

[install]
WantedBy=multi-user.target

 vi /etc/systemd/system/sonar.service #above add this lines
 systemctl status sonar
 systemctl status sonar

 sudo systemctl enable sonar
 sudo systemctl  start sonar
 installing process
 sonar